apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.containeroo.ch
    chart: local-path-provisioner
    targetRevision: 0.0.35 # Recommended: Check for the latest version
    helm:
      valueFiles:
      - $values/nucky-thompson/gitops/infra/values/local-path-provisioner.yaml
  - repoURL:  https://github.com/BeatGrate/homelab.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  syncPolicy:
    automated:
      prune: true # Allows ArgoCD to delete resources that are no longer in Git
      selfHeal: true # Allows ArgoCD to sync changes if the live state drifts from Git
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      # Automatically create the destination namespace if it doesn't exist
      - CreateNamespace=true
