apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.18.0 # Recommended: Check for the latest version
    helm:
      valueFiles:
      - $values/nucky-thompson/gitops/infra/values/sealed-secrets.yaml
  - repoURL:  https://github.com/BeatGrate/homelab.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true # Allows ArgoCD to delete resources that are no longer in Git
      selfHeal: true # Allows ArgoCD to sync changes if the live state drifts from Git
    syncOptions:
      # Automatically create the destination namespace if it doesn't exist
      - CreateNamespace=true

