apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: 1.92.5 # Recommended: Check for the latest version
    helm:
      valueFiles:
      - $values/nucky-thompson/gitops/infra/values/tailscale.yaml
  - repoURL:  https://github.com/BeatGrate/homelab.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/BeatGrate/homelab.git
    path: nucky-thompson/gitops/infra/sealed-secrets
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true # Allows ArgoCD to delete resources that are no longer in Git
      selfHeal: true # Allows ArgoCD to sync changes if the live state drifts from Git
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      # Automatically create the destination namespace if it doesn't exist
      - CreateNamespace=true

