apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-prom-grafana
  namespace: monitoring
spec:
  defaultBackend:
    service:
      name: kube-prometheus-kube-prome-grafana
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - grafana
