---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCS4HTuHxa9aCW5Rfn65f1M3bvEGlkYcKiWJwuiwUOkh28WY2CJZSPrui7UX9d7s5+4+eIN76DypLfQmG7uS+f3Ms8iUNNfuKNCELF4Pqde38DTuFb0++9lMGBEXslur0UnpJgpZMGwzaYjHFnz742P30G8g0KrTtSWM+TfcSymtbl/jsIFw+G0loAKkULE+nYZV21gE2SuoPpoCkBtt0DH/skihVdkL6esdv3TThXZfQqInK8IzsT9orYl9lf6WLLswbjHjI1sKM5zIJcvQyxd4XWH8GKhZ7Sijalu9GNiIK3KPr8/rqK0ICK2YsoE9Zn1eTuSfHcv/qnArocOItMHjzd3NIvRzSXv5WwgWhXey7X6eUceewTIE/SnM7k6ae1xwk5B5xrBG9z3uwzy1tIqnPeYWCSJmU9uRs9rg18sIbHaVsR0f365Hmm6zKBZPOAG7Bi+ScQXVoE4h4FtzjdvBnjLvN2QpqVAq1Bpan3hpgS9HVtfbodo3fqL7q+jGIItN8m/dpx5du4ZF2sUKXPbi0poQB1Vxnaho3KaCPk/A2n8NV2rStthvltsDlrv4ERYo13xFRmrxs/ieDZTnN/Scr4d/HnE5ar4nfEnoXNY0VEaoXhXpCobkLjoTR3Nscvx3ycJ4ZeVxEmzsvPws3q9Lu2MaeVc9Vl1NGGsKWz9usqSmWdniX9zhzxN/hCvlAca5DrRWmleq1c6nhKEpklnfw==
    client_secret: AgBgCxglFdZ14FUcxZ1aoUUMZpk6RjmUu2yetYo6vKqvXVqRqKXXmVihhtw1eg7z5cgzHaixrR9a0ctozt8oSgT5vLbErgdMhW81InuYfplQgNTHxhEsGzQGdyO0COEAOE2EUE4868Z5jcGC9YVxY1EABzqc++FIscigVxPDcIyLfcXv29byDUpD77W6l9vA2TOfIEl2d/yT7wTnjgNBC2QX/geVURxafAGYJU6tpZ1R/GLoMRugiGeftTmGo5rHV2NPai9zmr/R+2/GfFylL1Q+brgOAtX7EXwm7nGs6aaPCekvy/8ZaysrFx3x+pJk+iSSg4QQsI1dI+itPQ2nGZa4hZgf4vRcaor/zS3pDvo5/azw8BtswJWFzu55S/4c340103DXbSd8yPrB/B+jXjPmI6V4Vlg1oCVClfg6StPliGJvrzeTnFB0/kNhgzsCMfVoxJGE5Le+rYSmT0t2HLkMQaeQBc8UqSDT9RQiqk/RhyHdlOSN1+Y2UA4TV7QIag7Uqy3RE6N5g5RFRAyrJDO2qwmzZe4QvGzNkfiEpdc/uPqDNiu5Ixe6p3beoAduftrCyD+BmgpV8rQp+XMz10iqQ2XDQUymjGw0aVfsSskB1UvBKETDm+c9eJPfJ5A4hbHY5zqAWkHQvz7ACsym81+8UGPiHXikxCVNTeH+nQRjQZZJReBO0gF4PJdqyrPAiRDfrHGBQ7vWZ+SLQL1vF2dTgKSQl+PswV6g2cKwwSU8k21Ilit7DovLLTv90zIwEFQ8D/jMdts8uuKXVeng3FE=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
